name: Flutter Action

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.5'


      - run: flutter pub get
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v2
        with:
          name: book-tracker
          path: build/app/outputs/flutter-apk/app-release.apk
